--Adicionar grupo de consumo no Resource Plan

BEGIN

DBMS_RESOURCE_MANAGER.CLEAR_PENDING_AREA;
DBMS_RESOURCE_MANAGER.CREATE_PENDING_AREA;


DBMS_RESOURCE_MANAGER.CREATE_PLAN_DIRECTIVE (PLAN => 'IDUFF_PERGAMUM', 
     GROUP_OR_SUBPLAN => 'DEMAIS_SISTEMAS', COMMENT => 'Sistemas menos prioritarios', 
     CPU_P2 => 25);
     
DBMS_RESOURCE_MANAGER.VALIDATE_PENDING_AREA;
DBMS_RESOURCE_MANAGER.SUBMIT_PENDING_AREA;

end;