--Criar Resouce Plan Simples (Procedure da Oracle)


--BEGIN
--
--DBMS_RESOURCE_MANAGER.CREATE_SIMPLE_PLAN(SIMPLE_PLAN => 'UFF_INSCRICAO',
--   CONSUMER_GROUP1 => 'GRUPO_PRIORITARIO', GROUP1_CPU => 50,
--   CONSUMER_GROUP2 => 'PERGAMUM', GROUP2_CPU => 25,
--   CONSUMER_GROUP3 => 'GRUPO_SECUNDARIO', GROUP3_CPU => 25);
--   
--END;