--Atribuir usuário de banco à um grupo do Resource Plan:

BEGIN
DBMS_RESOURCE_MANAGER.CLEAR_PENDING_AREA;
DBMS_RESOURCE_MANAGER.CREATE_PENDING_AREA;
--
--DBMS_RESOURCE_MANAGER.SET_CONSUMER_GROUP_MAPPING  
--  (DBMS_RESOURCE_MANAGER.ORACLE_USER, 'IDUFF_DESENV', 'GRUPO_PRIORITARIO');
  
DBMS_RESOURCE_MANAGER.SET_CONSUMER_GROUP_MAPPING  
  (DBMS_RESOURCE_MANAGER.ORACLE_USER, 'IDUFF_HOMOLOG', 'GRUPO_PRIORITARIO');
    
--DBMS_RESOURCE_MANAGER.SET_CONSUMER_GROUP_MAPPING  
--    (DBMS_RESOURCE_MANAGER.ORACLE_USER, 'SYSPERGAMUM', 'PERGAMUM');
--    
--DBMS_RESOURCE_MANAGER.SET_CONSUMER_GROUP_MAPPING  
--    (DBMS_RESOURCE_MANAGER.ORACLE_USER, 'BIBINTERNET', 'PERGAMUM');
--    
--
--DBMS_RESOURCE_MANAGER.SET_CONSUMER_GROUP_MAPPING  
--    (DBMS_RESOURCE_MANAGER.ORACLE_USER, 'PERGAMUM_WEB_INT', 'PERGAMUM');

--DBMS_RESOURCE_MANAGER.SET_CONSUMER_GROUP_MAPPING  
  --  (DBMS_RESOURCE_MANAGER.ORACLE_USER, 'IDUFF_DESENV', 'GRUPO_PRIORITARIO');
  
    
--     
DBMS_RESOURCE_MANAGER.VALIDATE_PENDING_AREA;
DBMS_RESOURCE_MANAGER.SUBMIT_PENDING_AREA;
--
END;