--SELECT * FROM V$SESSION wHERE  BLOCKING_SESSION IS NOT NULL--  spwper_consultas
--sid in(215,806,951) 

-- SELECT * FROM V$sql where SQL_ID='33jrwmua9pta0';
--SELECT * FROM V$sql where SQL_ID='95d956xwzbf92';

--SELECT * FROM ALL_SOURCE --WHERE owner='SYSPERGAMUM' AND LOWER(NAME)='spwper_consultas';


 --select * from V$SESSION_WAIT
 
 --alter system set sga_target=3500M scope=spfile;
 --alter system set sga_max_size=4G scope=spfile;
 
--ALTER SYSTEM KILL SESSION '806,1096';
--SELECT * FROM V$ACTIVE_SESSION_HISTORY

--alter system set pga_aggregate_target=1200M scope=spfile;

--show parameter pga_aggregate_target;

----SELECT COUNT(*),USER_ID,USERNAME,DATA FROM( 
----SELECT DISTINCT SHY.USER_ID,DBA.USERNAME,TO_CHAR(SHY.SAMPLE_TIME,'DD/MM/YYYY') AS DATA,SHY.SESSION_ID,SHY.SESSION_SERIAL#
----  FROM V$ACTIVE_SESSION_HISTORY SHY
----  LEFT JOIN (SELECT USERNAME,USER_ID FROM DBA_USERS) DBA ON DBA.USER_ID=SHY.USER_ID
--      /*GROUP BY SHY.USER_ID,DBA.USERNAME,TO_CHAR(SHY.SAMPLE_TIME,'DD/MM/YYYY'),SHY.SESSION_ID,SHY.SESSION_SERIAL#*/) GROUP BY USER_ID,USERNAME,DATA ;


