--alter PROFILE DEFAULT LIMIT IDLE_TIME 180 ;

SELECT PLAN,COMMENTS,STATUS FROM DBA_RSRC_PLANS;

--BEGIN

--DBMS_RESOURCE_MANAGER.clear_pending_area;
--DBMS_RESOURCE_MANAGER.CREATE_PENDING_AREA;


--DBMS_RESOURCE_MANAGER.CREATE_SIMPLE_PLAN(SIMPLE_PLAN => 'IDUFF_PERGAMUM',
--   CONSUMER_GROUP1 => 'IDUFF_PRODUCAO', GROUP1_PERCENT => 50,
--   CONSUMER_GROUP2 => 'PERGAMUM', GROUP2_PERCENT => 25);
--END;

--DBMS_RESOURCE_MANAGER.VALIDATE_PENDING_AREA;
--DBMS_RESOURCE_MANAGER.SUBMIT_PENDING_AREA;



 
--EXEC DBMS_RESOURCE_MANAGER.CREATE_PENDING_AREA;
--EXEC DBMS_RESOURCE_MANAGER.VALIDATE_PENDING_AREA;
--EXEC DBMS_RESOURCE_MANAGER.SUBMIT_PENDING_AREA;
--
--BEGIN
--DBMS_RESOURCE_MANAGER.CLEAR_PENDING_AREA;
--DBMS_RESOURCE_MANAGER.CREATE_PENDING_AREA;
----
--DBMS_RESOURCE_MANAGER.SET_CONSUMER_GROUP_MAPPING  
--    (DBMS_RESOURCE_MANAGER.ORACLE_USER, 'IDUFF_PRODUCAO', 'IDUFF_PRODUCAO');
----     
--DBMS_RESOURCE_MANAGER.VALIDATE_PENDING_AREA;
--DBMS_RESOURCE_MANAGER.SUBMIT_PENDING_AREA;
----
--END;

--BEGIN
--DBMS_RESOURCE_MANAGER.CLEAR_PENDING_AREA;
--DBMS_RESOURCE_MANAGER.CREATE_PENDING_AREA;
--
--DBMS_RESOURCE_MANAGER.UPDATE_PLAN_DIRECTIVE(
--PLAN => 'IDUFF_PERGAMUM',
--group_or_subplan => 'PERGAMUM',
--new_cpu_p2 => 25);
--
--DBMS_RESOURCE_MANAGER.VALIDATE_PENDING_AREA;
--DBMS_RESOURCE_MANAGER.SUBMIT_PENDING_AREA;
--END;
--   CONSUMER_GROUP2 => 'PERGAMUM', GROUP2_PERCENT => 25);
--END;