DECLARE

MAX_VAL INTEGER;
SQL_TEXT VARCHAR2 (254);

BEGIN



FOR T IN (
select DBO.OWNER||'.'|| REPLACE(REPLACE(OBJECT_NAME,'_SEQ',''),'SEQ_','') AS TABELA,
OBJECT_NAME, SEQ.LAST_NUMBER AS ULTIMO_VALOR,SEQ.CACHE_SIZE,TABC.COLUMN_NAME


from dba_objects DBO,DBA_SEQUENCES SEQ,dba_tab_columns tabc



where DBO.OWNER=SEQ.SEQUENCE_OWNER

      AND DBO.OBJECT_NAME=SEQ.SEQUENCE_NAME
      AND dbo.owner='IDUFF_DESENV' AND dbo.OBJECT_TYPE='SEQUENCE' AND dbo.STATUS='VALID'
      and TABC.OWNER=DBO.OWNER
      and TABC.TABLE_NAME=REPLACE(REPLACE(OBJECT_NAME,'_SEQ',''),'SEQ_','')
      and TABC.DATA_TYPE='NUMBER'
      AND TABC.COLUMN_NAME LIKE 'ID%') LOOP
--(SELECT LAST_NUMBER FROM DBA_SEQUENCES WHERE SEQUENCE_NAME= DBO.OBJECT_NAME AND SEQUENCE_OWNER=DBO.OWNER) AS ULTIMO_VALOR

SQL_TEXT:= 'SELECT MAX('||T.COLUMN_NAME||') FROM ' || T.TABELA;
EXECUTE IMMEDIATE SQL_TEXT INTO MAX_VAL;
DBMS_OUTPUT.PUT_LINE(T.TABELA||','||
T.OBJECT_NAME||','||
T.ULTIMO_VALOR||','||
T.CACHE_SIZE||','||
T.COLUMN_NAME||','||
MAX_VAL);

END LOOP;

END;