--show parameter version;

--SELECT * FROM V$VERSION

SELECT * FROM DBA_FEATURE_USAGE_STATISTICS


--BEGIN DBMS_OUTPUT.PUT_LINE(DBMS_DB_VERSION.VERSION || '.' || DBMS_DB_VERSION.RELEASE); END;

--select * from PRODUCT_COMPONENT_VERSION;